version : "3.8"

services:
  app_ui:
    build:
      context: ../UI/AppUI
      dockerfile: Dockerfile
    container_name: app_ui
    command: sh -c "npm ci && npm run build --prod && npm start"
    volumes:
      - ../UI/AppUI:/app
    expose:
      - "4200"
    ports:
      - "4200:4200"
    networks:
      - app-network

  # user db and user mgr service
  user_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_database
    networks:
      - user-network
    expose:
      - "3306"
    deploy:
      resources:
        limits:
          memory: 1G
    volumes:
      - user_db_data:/var/lib/mysql

  user_mgr:
    build:
      context: ../BL/user_mgr
      dockerfile: Dockerfile
    environment:
      DB_NAME: user_database
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: user_db
    volumes:
      - ../BL/user_mgr:/app
    container_name: user_mgr
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - nginx_server
      - user_db
    ports:
      - "8000:8000"
    expose:
      - "8000"
    networks:
      - user-network
      - app-network

# group db and group mgr service
  group_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: group_database
    networks:
      - group-network
    expose:
      - "3306"
    deploy:
      resources:
        limits:
          memory: 1G

  group_mgr:
    build:
      context: ../BL/group_mgr
      dockerfile: Dockerfile
    environment:
      DB_NAME: group_database
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
    volumes:
      - ../BL/group_mgr:/app
    container_name: group_mgr
    command: python manage.py runserver 0.0.0.0:8001
    depends_on:
      - nginx_server
      - group_db
    ports:
      - "8001:8001"
    expose:
      - "8001"
    networks:
      - group-network
      - app-network
# expense db and expense mgr service
  expense_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expense_database
    networks:
      - expense-network
    expose:
      - "3306"
    deploy:
      resources:
        limits:
          memory: 1G

  expense_mgr:
    build:
      context: ../BL/expense_mgr
      dockerfile: Dockerfile
    environment:
      DB_NAME: expense_database
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
    volumes:
      - ../BL/expense_mgr:/app
    container_name: expense_mgr
    command: python manage.py runserver 0.0.0.0:8002
    depends_on:
      - nginx_server
      - expense_db
    ports:
      - "8002:8002"
    expose:
      - "8002"
    networks:
      - expense-network
      - app-network
# nginx server
  nginx_server:
    build:
      context: ../Infra
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: nginx_server
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ../Infra/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ../Infra/nginx/conf/conf.d:/etc/nginx/conf.d

volumes:
  user_db_data:
    driver: local
  group_db_data:
    driver: local
  expense_db_data:
    driver: local
networks:
  app-network:
    driver: bridge
  user-network:
    driver: bridge
  group-network:
    driver: bridge
  expense-network:
    driver: bridge